sudo: required

services:
  - docker

env:
  - SOLR_HOST=my_solr:8983

before_install:
  - docker network create mynet
  - docker run --net mynet --name my_solr -d -p 8983:8983 -t solr:7.3-alpine solr-create -c scxa-analytics-v2

install:
  - docker build -t test/index-scxa-module .

script:
  - sleep 20
  - docker exec -it --user=solr my_solr bin/solr create_core -c scxa-gene2experiment-v1
  - docker run -i --net mynet -v $( pwd )/tests:/usr/local/tests -e SOLR_HOST=$SOLR_HOST --entrypoint=/usr/local/tests/run_tests_inside_container.sh test/index-scxa-module
  - bash tests/run-tests.sh
