name: Test scxa-index

on: [pull_request]

jobs:
  setup:
    name: "Test with containers"
    # runs-on: "ubuntu-latest"
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          ./run_tests_in_containers.sh
